services:
  #db
  db: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: studentplanner-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - "14330:1433"
    expose:
      - "1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 10

  #backend
  backend:
    build: ./StudentPlanner.Backend
    container_name: studentplanner-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: "Server=db;Database=StudentPlanner;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True"
      AllowedOrigins__0: "http://localhost:3001"
      Jwt__Audience: "http://localhost:3001"
      Jwt__Issuer: "http://localhost:8080"
      Jwt__SecretKey: "exemplaryKey_afaosfiajo8ug983j0cm0oxdjq2owkzihlmkjb79ockjdyk9c0m"
      UsosApi__BaseUrl: "http://usos-api:3000"
      EmailSettings__SmtpUsername: ${MAILTRAP_USERNAME}
      EmailSettings__SmtpPassword: ${MAILTRAP_PASSWORD}
      EmailSettings__SmtpServer: "sandbox.smtp.mailtrap.io"
      EmailSettings__SmtpPort: 2525

    
    ports:
      - "8080:8080"
    depends_on:
      db: 
        condition: service_healthy
  
  #usos-api
  usos-api:
    build: ./usos-api
    container_name: usos-api
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - ./usos-api/.env
    volumes:
      - ./usos-api/storage:/app/storage
    restart: unless-stopped

  #frontend
  frontend:
    build:
      context: ./StudentPlanner.Frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: studentplanner-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mssql-data: