name: Build and analyze

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore "./Student Planner/StudentPlanner.Backend/StudentPlanner.Backend.slnx"

      - name: Check format
        run: dotnet format "./Student Planner/StudentPlanner.Backend/StudentPlanner.Backend.slnx" --verify-no-changes

      - name: Build and analyze
        run: dotnet build "./Student Planner/StudentPlanner.Backend/StudentPlanner.Backend.slnx" -c Release /p:TreatWarningsAsErrors=true
